### ISSUE TITLE
Class 'AclPermission' not found !

### ISSUE THREAD

**Issue by m-alinasab** [Volicon/laravel-acl-rbac#6]
Hi there.

As I teach, I installed the package, but there are several problems:
  1 - Enter the following code, I get the error
php artisan acl: install
The tables will be created and displays the following message:
Nothing to migrate.

Create a route I've put the following content:

Route::get('add' , function(){
	$role = new AclRole([
	    'name' => 'product managers',
	    'permissions' => [
	        new AclPermission('products.manage',[],true)
	    ]
	]);
	$role->add();

	$user = User::first();
	$aclUser = new AclUser($user);
	$aclUser->setRoles(3); 

});

After the call path, the following error was encountered:
Class 'AclPermission' not found

Please create a video tutorial to learn how to package.

Thank you.

**Comment by nadavvin** [comment]
1) I will check soon

2) You can use \Volicon\Acl\AclPermission or add it to the alias.
But this is not the way to add permissions to role.

You should add the permissions in the config:
https://github.com/Volicon/laravel-acl-rbac#configuration

and then run php artisan acl:update

To add the permissions to the role:
$role = new AclRole([
'name' => 'product managers',
'permissions' => [
  ["resource" => "products.manage", "values" => []   ,"allowed" => true ],
]
]);
$role->add();

});

**Comment by m-alinasab** [comment]
Thanks for your reply.
Is it possible to get a tutorial video?
There is no problem in the installation process, but the amount and accessibility, not a complete description!

**Comment by nadavvin** [comment]
There was a problems in running the migrations.
I fixed now so you can run composer update.

I will first create presentation for using the package.
